### ISSUE TITLE
How can I load the data into an external Elastic Search instance?

### ISSUE THREAD

**Issue by aflinton** [IHTSDO/health-data-analytics#1]
Looking to try this out but would like to be able to use an external Elastic Search Instance. Wondering if there is a how-to / example config/ any notes on if a specific version of es must be used etc.

Thanks

**Comment by kaicode** [comment]
Hi @aflinton I've provided some example configuration in [application.properties](https://github.com/IHTSDO/health-data-analytics/blob/master/src/main/resources/application.properties)

**spring.data.elasticsearch.cluster-nodes** comes from the common application properties for version 1.5.1 of Spring Boot.
 https://docs.spring.io/spring-boot/docs/1.5.1.RELEASE/reference/html/common-application-properties.html
Cheers.

**Comment by kaicode** [comment]
Please star the repo if you find it useful! Thanks.
