### ISSUE TITLE
Error on some ElasticSearch field annotations

### ISSUE THREAD

**Issue by DMMN1992** [IHTSDO/health-data-analytics#2]
I get org.elasticsearch.index.mapper.MapperParsingException: No type specified for field [dob] for field _dob_ on Patient.java.
This exception also occurs for field _gender_ (also on Patient.java) and on fields _name_ and _description_ of file CohortCriteria.java.

Specifically the annotation seems to lack the _type_ added to it, at least for me.

<img width="1585" alt="Error" src="https://user-images.githubusercontent.com/9169606/40334122-e4b52ae6-5d53-11e8-942c-cefb38cae692.png">

**Comment by kaicode** [comment]
Hi @DMMN1992 . Thank you for raising this and for the pull request! That's merged now.
