### ISSUE TITLE
Failure to find org.ihtsdo.otf:snomed-boot:jar:1.1.0

### ISSUE THREAD

**Issue by johngrimes** [IHTSDO/health-data-analytics#9]
The artifact `org.ihtsdo.otf:snomed-boot` does not seem to be currently present in the repository: https://nexus3.ihtsdotools.org/repository/maven-releases/

Also, I can't build it from https://github.com/IHTSDO/snomed-boot, as `1.1.0` is not the subject of a tagged commit.

**Comment by johngrimes** [comment]
Worked around by building at IHTSDO/snomed-boot@b15b579.

**Comment by kaicode** [comment]
Thanks for finding a workaround. We'll get this fixed.

**Comment by kaicode** [comment]
The latest uses snomed-boot 2.2.0 which is in the public maven repo.
